# Generated by Django 5.2.8 on 2025-11-14 17:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lfapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='claimed_at',
            field=models.DateTimeField(blank=True, help_text='When the item was claimed', null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='claimed_by',
            field=models.ForeignKey(blank=True, help_text='User who claimed this item', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='claimed_items', to=settings.AUTH_USER_MODEL),
        ),
    ]
