# Generated by Django 5.2.8 on 2025-11-15 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lfapp', '0002_item_claimed_at_item_claimed_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='display_name',
            field=models.BooleanField(default=False, help_text='Display poster name publicly (required for found items)'),
        ),
    ]
