# Generated by Django 5.2.8 on 2025-11-15 10:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lfapp', '0003_item_display_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('subject', models.CharField(help_text='Message subject', max_length=200)),
                ('message', models.TextField(help_text='Message content')),
                ('sender_phone', models.CharField(blank=True, default='', help_text='Optional contact phone number', max_length=20)),
                ('is_read', models.BooleanField(default=False, help_text='Has recipient read this message')),
                ('item', models.ForeignKey(help_text='The item this message is about', on_delete=django.db.models.deletion.CASCADE, related_name='contact_messages', to='lfapp.item')),
                ('recipient', models.ForeignKey(help_text='User who receives the message', on_delete=django.db.models.deletion.CASCADE, related_name='received_messages', to=settings.AUTH_USER_MODEL)),
                ('sender', models.ForeignKey(help_text='User who sent the message', on_delete=django.db.models.deletion.CASCADE, related_name='sent_messages', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Contact Message',
                'verbose_name_plural': 'Contact Messages',
                'ordering': ['-created_at'],
            },
        ),
    ]
