# Generated by Django 5.2.8 on 2025-11-15 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lfapp', '0004_contactmessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Whether the item is listed publicly (users can delist their posts)'),
        ),
    ]
