# Generated by Django 5.2.8 on 2025-11-16 18:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lfapp', '0005_item_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactmessage',
            name='image',
            field=models.ImageField(blank=True, help_text='Optional image attachment', null=True, upload_to='message_images/'),
        ),
        migrations.AddField(
            model_name='contactmessage',
            name='parent_message',
            field=models.ForeignKey(blank=True, help_text='Parent message if this is a reply', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='lfapp.contactmessage'),
        ),
    ]
