# Generated by Django 5.2.8 on 2025-11-19 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lfapp', '0006_contactmessage_image_contactmessage_parent_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='contact_number',
            field=models.CharField(blank=True, default='', help_text='Optional contact number for this item', max_length=20),
        ),
    ]
