# Generated by Django 5.2.8 on 2025-11-20 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lfapp', '0007_item_contact_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='completed_at',
            field=models.DateTimeField(blank=True, help_text='When the item was marked as found/claimed by the poster', null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='completion_email',
            field=models.EmailField(blank=True, default='', help_text='Email of person who claimed or returned the item', max_length=254),
        ),
        migrations.AddField(
            model_name='item',
            name='completion_name',
            field=models.CharField(blank=True, default='', help_text='Name of person who claimed (for found items) or returned (for lost items) the item', max_length=200),
        ),
        migrations.AlterField(
            model_name='item',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending Approval'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('claimed', 'Claimed'), ('found', 'Found/Recovered')], default='pending', max_length=10),
        ),
    ]
