# Generated by Django 5.2.8 on 2025-11-23 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lfapp', '0008_item_completed_at_item_completion_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='google_profile_picture',
            field=models.URLField(blank=True, default='', help_text='Profile picture URL from Google', max_length=500),
        ),
    ]
