# Generated by Django 5.2.8 on 2025-11-28 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lfapp', '0009_customuser_google_profile_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactmessage',
            name='is_deleted',
            field=models.BooleanField(default=False, help_text='Has sender deleted this message'),
        ),
    ]
