# Generated by Django 5.2.8 on 2025-11-28 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lfapp', '0010_contactmessage_is_deleted'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactmessage',
            name='deleted_by_recipient',
            field=models.BooleanField(default=False, help_text='Has recipient deleted this thread from their view'),
        ),
        migrations.AddField(
            model_name='contactmessage',
            name='deleted_by_sender',
            field=models.BooleanField(default=False, help_text='Has sender deleted this thread from their view'),
        ),
    ]
