# Generated by Django 5.2.8 on 2025-12-13 14:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lfapp', '0011_contactmessage_deleted_by_recipient_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='archive_notes',
            field=models.TextField(blank=True, default='', help_text='Additional notes about why item was archived'),
        ),
        migrations.AddField(
            model_name='item',
            name='archive_reason',
            field=models.CharField(blank=True, choices=[('spam', 'Spam'), ('inappropriate', 'Inappropriate content'), ('duplicate', 'Duplicate post'), ('resolved', 'Resolved/No longer needed'), ('other', 'Other')], default='', help_text='Reason for archiving', max_length=20),
        ),
        migrations.AddField(
            model_name='item',
            name='archived_at',
            field=models.DateTimeField(blank=True, help_text='When the item was archived by admin', null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='archived_by',
            field=models.ForeignKey(blank=True, help_text='Admin who archived this item', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='archived_items', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='item',
            name='is_archived',
            field=models.BooleanField(default=False, help_text='Whether the item was archived/deleted by admin'),
        ),
    ]
