# Generated by Django 5.2.8 on 2025-12-13 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lfapp', '0012_item_archive_notes_item_archive_reason_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='content_updated_at',
            field=models.DateTimeField(blank=True, help_text='When the item content was last edited by the poster', null=True),
        ),
    ]
